server:
 port: 8090
mybatis:
 mapper-locations: # 所有的mapper映射文件
 - classpath:mapping/*.xml
spring:
 application:
  name: trycloud-provider-users
eureka:
 client:
  service-url:
   defaultZone: http://fxy:1234@eureka1:7001/eureka,http://fxy:1234@eureka2:7002/eureka,http://fxy:1234@eureka3:7003/eureka
 instance:
  instance-id: trycloud-provider-users
  prefer-ip-address: true
  lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
  lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
info:
  app.name: microcloud-provider-users
  company.name: fxy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
management:
  endpoints:
    web:
      exposure:
        include: '*'
 