server:
 port: 8082
mybatis:
 mapper-locations: # 所有的mapper映射文件
 - classpath:mapping/*.xml
spring:
 application:
  name: trycloud-provider-product
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
   driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
   url: jdbc:mysql://localhost:3306/springcloud3?serverTimezone=GMT%2B8 # 数据库连接地址
   username: root # 数据库用户名
   password: mysql # 数据库连接密码
# security:
#  user:
#   name: admin
#   password: fxy
#   roles:
#    - USER
eureka:
 client:
  service-url:
   defaultZone: http://fxy:1234@eureka1:7001/eureka,http://fxy:1234@eureka2:7002/eureka,http://fxy:1234@eureka3:7003/eureka
 instance:
  instance-id: trycloud-provider-product3
  prefer-ip-address: true
  lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
  lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
info:
  app.name: microcloud-provider-product3
  company.name: fxy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
 