server:
  port: 80
spring:
  application:
    name:  trycloud-consumer-feign-hystrix
  zipkin:
    base-url: http://localhost:8601 #所有的数据提交到此服务之中
    sender:
      type: web       #提交的类型是web 服务
  sleuth:
    sampler:
      probability: 1.0 # 定义抽样比率，默认为0.1


feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: # 可以被压缩的类型
       - text/xml
       - application/xml
       - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩

logging:
 level:
  org.trycloud.service: DEBUG

eureka:
  client:
    register-with-eureka: false
    service-url:
        defaultZone: http://fxy:1234@eureka1:7001/eureka,http://fxy:1234@eureka2:7002/eureka,http://fxy:1234@eureka3:7003/eureka