server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://fxy:1234@eureka1:7001/eureka,http://fxy:1234@eureka2:7002/eureka,http://fxy:1234@eureka3:7003/eureka
    register-with-eureka: true
  instance:
    instance-id: trycloud-zull-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
   

spring:
  application:
    name:  trycloud-zull-gateway
  security:
    user:
      name: fxy
      password: 123456
  zipkin: 
    base-url: http://localhost:8601#所有的数据提交到此服务之中
    sender: 
    type: web #提交的类型是web 服务
  sleuth: 
    sampler: 
     probability: 1.0 # 定义抽样比率，默认为0.1
zuul:
 routes:
  trycloud-provider-users: /user-proxy/**
  product:
   path: /product-proxy/**
   serviceId: trycloud-provider-product
 ignored-services: "*"
 prefix: /trycloud